### ISSUE TITLE
Even after successful record it's throwing the error

### ISSUE THREAD

**Issue by Rajagopalan-M** [kapoorlakshya/ffmpeg-screenrecorder#34] opened 2019-02-03 14:59 UTC
Hi, My recording is successfully happening for firefox. But even after the successful recording, it throws the following error

> FFMPEG::Error: [libx264 @ 00000225731ae940] ref B L1: 95.2%  4.8%
>  [libx264 @ 00000225731ae940] kb/s:192.70
> 

And May I know this recorder can be used for Chrome as well? I haven't gotten any success with chrome yet. If it can be done, Can you let me know how that is?

**Comment by kapoorlakshya** [comment] 2019-02-03 19:18
Hi @Rajagopalan-M, thanks for reporting this. I'll need some more details to properly troubleshoot this. Can you please share the following information?

- Operating System
- `opts` Hash used for the recorder
- ffmpeg log file as a gist or on pastebin
- Re-run the recorder with `log_level: Logger::DEBUG` and share the console output

The recorder should work with almost all applications. You can retrieve the active window title by passing in the application exe name. For Chrome, it will be '`chrome'`:

```ruby
FFMPEG::WindowTitles.fetch 'chrome'
=> ["Google - Google Chrome"]
```

The limitation here is that this only works as expected if only one application (browser) window is open as it only returns the title of the currently active tab. After your test launches the browser, use `FFMPEG::WindowTitles.fetch ('chrome').first` as `input` to get a handle on the very first window (website 
 title) that opens. After this, the recorder will capture everything in that window, including any new tabs that you open. This will not work if you open new windows though. Use `input: 'desktop'` if you want to capture multiple application windows.

**Note**: You may experience #35 which I just caught. Will push a fix for this very soon.

**Comment by kapoorlakshya** [comment] 2019-02-08 08:26
@Rajagopalan-M Are you still getting the error?

**Comment by Rajagopalan-M** [comment] 2019-02-08 20:02
@kapoorlakshya 

Hi, Yes, but I am rescued this way so it's not showing up.

> @recorder.stop rescue ''

**Comment by Rajagopalan-M** [comment] 2019-02-08 20:03
> Hi @Rajagopalan-M, thanks for reporting this. I'll need some more details to properly troubleshoot `FFMPEG::Error`. Can you please share the following information?
> 
> * Operating System
> * `opts` Hash used for the recorder
> * ffmpeg log file as a gist or on pastebin
> * Re-run the recorder with `log_level: Logger::DEBUG` and share the console output
> 
> The recorder should work with almost all applications. You can retrieve the active window title by passing in the application exe name. For Chrome, it will be `"chrome"`:
> 
> ```ruby
> FFMPEG::WindowTitles.fetch 'chrome'
> => ["Google - Google Chrome"]
> ```
> 
> The limitation here is that this only works as expected if only one application (browser) window is open. Otherwise, it returns the title of active tabs from all processes and may not use the expected window. After your test launches the browser, use `FFMPEG::WindowTitles.fetch ('chrome').first` as `input` to get a handle on the very first window (website title) that opens. After this, the recorder will capture everything in that window, including any new tabs that you open. Please note that this will not capture any new windows that may open. Use `input: 'desktop'` if you want to capture multiple application windows.

Give me some time, I will get back to this. 

Please refer my previous message as well.

**Comment by kapoorlakshya** [comment] 2019-02-09 06:13
Hi @Rajagopalan-M, I am glad you are able to make it work by rescuing the error, but my concern is that the error should not be raised if the recording is successful. I am unable to reproduce it on Windows 10 or on Linux, so I am curious why you are expereincing it.

Thanks for taking out the time to give me the info. Looking forward to troubleshooting this.

**Comment by Rajagopalan-M** [comment] 2019-02-09 06:15
@kapoorlakshya  I understood. But how would I help you? Should I run with 

    * Re-run the recorder with `log_level: Logger::DEBUG` and share the console output

And send the report?

**Comment by kapoorlakshya** [comment] 2019-02-09 06:21
Yes, that and the following information:

* Operating System
* `opts` Hash used to initialize the recorder
* Contents of `ffmpeg.log` file

**Comment by Rajagopalan-M** [comment] 2019-02-09 06:39
Operating System : Windows 10

Hash:
```
opts = {input: FFMPEG::WindowTitles.fetch('firefox').first,
                    output: File.expand_path("Output/Video/#{scenario}/#{testCase.first + '_' + testCase[1]}.mp4"),
                    framerate: 15,
                    log_level: Logger::DEBUG}
```
Gist of ffmpeg.log is here

https://gist.github.com/Rajagopalan-M/2e7cad1969d4fb48e3dd0060f00aab06

**Comment by kapoorlakshya** [comment] 2019-02-09 06:48
Thanks for the information. I looked at the `ffmpeg.log` and looks like FFmpeg is raising an error on lines 275-276, which is why you are seeing `FFMPEG::Error`.

```
[gdigrab @ 0000019075e0a540] Failed to capture image (error 8)
title=AllianzGo - Mozilla Firefox: I/O error
```

Are you closing the browser before stopping the recorder? If yes, then you need to stop the recorder right before closing the browser.

**Comment by Rajagopalan-M** [comment] 2019-02-09 06:59
@kapoorlakshya 

You are absolutely correct, yes, I am closing the recorder after the browser has been closed. Wait, let me rewrite the program and let you know whether it works. Thanks.

**Comment by Rajagopalan-M** [comment] 2019-02-09 07:22
@kapoorlakshya  Dude, you are right with your thinking. Yes, it's working fine now. You can close this thread.

**Comment by kapoorlakshya** [comment] 2019-02-09 09:14
@Rajagopalan-M Awesome! Glad we figured it out. There are a few more limitations when recording a window, and I have listed these in the README.

**Closed by kapoorlakshya** 2019-02-09 09:14 UTC

**Comment by Rajagopalan-M** [comment] 2019-02-09 11:02
Okay, thank you.
